version: 2
updates:
  - package-ecosystem: workflow-wait-action
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pnpm
    directory: /
    schedule:
      interval: weekly
