name: workflow-1

on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - .github/workflows/workflow-1.yml

jobs:
  workflow_1:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow 1 Test
        shell: bash
        run: |
          date
          echo "sleep 15s"
          sleep 15
          date
