name: workflow-2

on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - .github/workflows/workflow-2.yml

jobs:
  workflow_2:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow 2 Test
        shell: bash
        run: |
          date
          echo "sleep 45s"
          sleep 45
          date
